import { MissingPerson } from "@/types";

export default [
  {
    "id": "16699a39-0dde-4fa6-ad61-65861b64c7b2",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "2 ילדות של משפחת כץ",
    "First Name": "2 ילדות",
    "Last Name": "כץ",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "נמצא",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "יוני אשר",
    "Reporter relation": "NA",
    "Reporter Phone": "502006090",
    "Reporter Email": "yonia177@gmail.com",
    "Last hour of contact": "11:00",
    "Report from reporter": "אפרת כץ. דורון אשר כץ. ו 2 ילדות קטנות",
    "Last seen location": "ניר עוז",
    "Last Seen Comments": "קיבוץ ניר עוז",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  },
  {
    "id": "b43fecb7-9c6b-4b6d-8ac0-be09361d0899",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Adi Kaploun",
    "First Name": "Adi",
    "Last Name": "Kaploun",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "Leah Evin",
    "Reporter relation": "NA",
    "Reporter Phone": "502333678",
    "Reporter Email": "leahevin85@gmail.com",
    "Last hour of contact": "הבוקר",
    "Report from reporter": "הם מחולית בעוטף עזה   בעלה היה בכיתת כוננות והיא נשארה עם הילדים.  את הילדים מצאו ליד הגבול ואותה לא מוצאים",
    "Last seen location": "חולית",
    "Last Seen Comments": "חולית",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  },
  {
    "id": "c34a3e41-590b-4bd1-8905-55d0cb29ff14",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Amit Magnezi",
    "First Name": "Amit",
    "Last Name": "Magnezi",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "de",
    "Reporter relation": "NA",
    "Reporter Phone": "0523131616 0523136767",
    "Reporter Email": "NA",
    "Last hour of contact": "שבת בבוקר",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "מסיבת טבע בנובה",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "NA",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "קעקוע בכתף ימין צורת שמש גדולה",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  },
  {
    "id": "9f62fb77-7881-431d-879b-47e02b96c997",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Angelyn Aguirre",
    "First Name": "Angelyn",
    "Last Name": "Aguirre",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "הרוג",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Angenica Aguirre",
    "Reporter relation": "NA",
    "Reporter Phone": "548847342",
    "Reporter Email": "peraltagenica@gmail.com",
    "Last hour of contact": "Yesterday 8:00am",
    "Report from reporter": "NA",
    "Last seen location": "קיבוץ כפר עזה",
    "Last Seen Comments": "Kibbutz kfar Aza",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  },
  {
    "id": "e9ccbd9f-d592-426d-be9a-43f962cc21d6",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Damaris Raab (מריסה)",
    "First Name": "Damaris",
    "Last Name": "Raab (מריסה)",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "חטוף",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "דגמר שלו",
    "Reporter relation": "NA",
    "Reporter Phone": "549760256",
    "Reporter Email": "eliyalavi1@gmail.com",
    "Last hour of contact": "אתמול בערב",
    "Report from reporter": "\"מתנדבת מגרמניה",
    "Last seen location": " הייתה אמורה לחזור הביתה אתמול היה הקשר האחרון איתה בזמן שהתחבאה בממ״ד מאז הקשר אבד\"",
    "Last Seen Comments": "לא ידוע",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "אזרח",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "גוון בהיר",
    "Hair Color": "בהיר",
    "Height": "בהיר",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA"
  },
  {
    "id": "e96518e9-cfed-4dab-8182-dffb6cd46a54",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Gali Taraschansky",
    "First Name": "Gali",
    "Last Name": "Taraschansky",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Viktoria",
    "Reporter relation": "NA",
    "Reporter Phone": "+79647077949",
    "Reporter Email": "chervonnaya.vp@gmail.com",
    "Last hour of contact": "07.10.2023 11:30",
    "Report from reporter": "child disappeared on the territory of kibbutz beeri as a result of escaping from terrorists",
    "Last seen location": "beeri",
    "Last Seen Comments": "beeri",
    "SoldierOrCivilian": "אזרח",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V"
  },
  {
    "id": "11755889-d8ce-4069-9f24-95bd4fd81aba",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Karla Stelzer Mendes",
    "First Name": "Karla",
    "Last Name": "Stelzer Mendes",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "Patricia Hallak",
    "Reporter relation": "NA",
    "Reporter Phone": "0506568111 0533334860",
    "Reporter Email": "patyhallak@hotmail.com  Filipasantoscosta@gmail.com",
    "Last hour of contact": ": בשעה 8:11 היא שלחה אודיו בוואטסאפ",
    "Report from reporter": "היא הייתה במסיבה בדרום. שלח אודיו ווידאו כשהוא נמלט. באודיו האחרון היא אמרה שהיא הייתה בבונקר שבו טרוריסטים זרקו פצצה והיא הצליחה להימלט  She is Brazilian  She was with the boyfriend in the party his name is Gabi Azulay- also still missing ! Please fast let me know something !!!",
    "Last seen location": "מסיבה בדרום",
    "Last Seen Comments": "היא הייתה במסיבה בדרום",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "בהיר",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  },
  {
    "id": "63c2299f-824c-471b-ab45-88787114ceed",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Lior Taraschansky",
    "First Name": "Lior",
    "Last Name": "Taraschansky",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Viktoria",
    "Reporter relation": "NA",
    "Reporter Phone": "+79647077949",
    "Reporter Email": "chervonnaya.vp@gmail.com",
    "Last hour of contact": "07.10.2023 11:30 a.m",
    "Report from reporter": "a child was left in a burning house on the territory of Kibbutz Beeri",
    "Last seen location": "Beeri",
    "Last Seen Comments": "Beeri",
    "SoldierOrCivilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V"
  },
  {
    "id": "b184c210-7aac-44ed-9c1f-d63703965318",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Lorie Alacre",
    "First Name": "Lorie",
    "Last Name": "Alacre",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "נעדר",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "נועם סולומון",
    "Reporter relation": "NA",
    "Reporter Phone": "506623329",
    "Reporter Email": "noamsw88@gmail.com",
    "Last hour of contact": "\"אתמול בשעות הבוקר המוקדמות",
    "Report from reporter": " אחותה מהפיליפינים דיברה איתה\"",
    "Last seen location": "\"החבר שהיא היתה איתו",
    "Last Seen Comments": " מאושפז בבית חולים ברזילי במחלקה הכירורגית כי נפגע מירי בגב",
    "SoldierOrCivilian": " אין פרטים מה קורה ללורי שלי :(\"",
    "Military ID (Mispar Ishi)": "\"בין נתיבות לאשקלון",
    "Address": " ליד מטה בוטנים\"",
    "Physical description": "\"בין נתיבות לאשקלון",
    "Eye color": " ליד מטה בוטנים\"",
    "Hair Color": "לא ידוע",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "גוון בהיר",
    "Marks on the body": "כהה",
    "Social Media": "כהה",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA"
  },
  {
    "id": "e7dc0168-4710-452b-bdac-def9dc7e34d1",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Orion hernandez",
    "First Name": "Orion",
    "Last Name": "hernandez",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "רתם כהן",
    "Reporter relation": "NA",
    "Reporter Phone": "506500922",
    "Reporter Email": "Jesus6853@gmail.com",
    "Last hour of contact": "במסיבה ברעים",
    "Report from reporter": "בחור מקסיקני לא דובר עברית כל המשפחה שלו במקסיקו אני האיש הקשר שמקושר עם המשפחה שלו וחברה שלו הישראלית נרצחה ונרצחה באירוע של הנובה",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "במסיבה ברעים",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "\"קעקועים על כל הידיים",
    "Social Media": " טרייבלים עד הצוואר כולל. כתובת בערבית על החזה.\"",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA"
  },
  {
    "id": "0fbb7b87-aebb-4446-bfce-98dec5852ca2",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Ranani Glazer / רנני גלזר",
    "First Name": "Ranani",
    "Last Name": "Glazer",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע    זכר",
    "Reporter name": "Jussara martins    דניאל",
    "Reporter relation": "NA",
    "Reporter Phone": "0506798027 0506710235    523624190",
    "Reporter Email": "Jussara_copa@gmail.com",
    "Last hour of contact": "09:30    לפני המסיבה של נובה",
    "Report from reporter": "הוא יהודי שגר בפורטו אלגרו והגיע לישראל עםעוד תיירת ששמה לא ידוע",
    "Last seen location": "דרום",
    "Last Seen Comments": "לא    דרום",
    "SoldierOrCivilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה    גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "\"קעקוע גדול על בית החזה",
    "Social Media": " שני קעקועים על זרוע ימין קעקוע במרכז הבטן     קעקוע גדול על החזה ידיים (כמו בקפלה הסיסטנית)",
    "Data to verify": " קעקועים גדולים על זרוע עליונה\"",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA"
  },
  {
    "id": "10488e19-6514-48ac-ab12-e8646c04a1fb",
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Soslyuk Vadym",
    "First Name": "Soslyuk",
    "Last Name": "Vadym",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "Soslyuk Stanislav",
    "Reporter relation": "NA",
    "Reporter Phone": "+79093196144",
    "Reporter Email": "v.gorelnikova@gmail.com",
    "Last hour of contact": "3  month ago",
    "Report from reporter": "Citizen of Ukrain . He can be in a jail.",
    "Last seen location": "Haifa",
    "Last Seen Comments": "Haifa",
    "SoldierOrCivilian": "אזרח",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "NA",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X"
  }
];