export default sampleData = [
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "2 ילדות של משפחת כץ",
    "First Name": "2 ילדות",
    "Last Name": "כץ",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "יוני אשר",
    "Reporter relation": "NA",
    "Reporter Phone": "502006090",
    "Reporter Email": "yonia177@gmail.com",
    "Last hour of contact": "11:00",
    "Report from reporter": "אפרת כץ. דורון אשר כץ. ו 2 ילדות קטנות",
    "Last seen location": "ניר עוז",
    "Last Seen Comments": "קיבוץ ניר עוז",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Adi Kaploun",
    "First Name": "Adi",
    "Last Name": "Kaploun",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "Leah Evin",
    "Reporter relation": "NA",
    "Reporter Phone": "502333678",
    "Reporter Email": "leahevin85@gmail.com",
    "Last hour of contact": "הבוקר",
    "Report from reporter": "הם מחולית בעוטף עזה   בעלה היה בכיתת כוננות והיא נשארה עם הילדים.  את הילדים מצאו ליד הגבול ואותה לא מוצאים",
    "Last seen location": "חולית",
    "Last Seen Comments": "חולית",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Amit Magnezi",
    "First Name": "Amit",
    "Last Name": "Magnezi",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "de",
    "Reporter relation": "NA",
    "Reporter Phone": "0523131616 0523136767",
    "Reporter Email": "NA",
    "Last hour of contact": "שבת בבוקר",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "מסיבת טבע בנובה",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "NA",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "קעקוע בכתף ימין צורת שמש גדולה",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Angelyn Aguirre",
    "First Name": "Angelyn",
    "Last Name": "Aguirre",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Angenica Aguirre",
    "Reporter relation": "NA",
    "Reporter Phone": "548847342",
    "Reporter Email": "peraltagenica@gmail.com",
    "Last hour of contact": "Yesterday 8:00am",
    "Report from reporter": "NA",
    "Last seen location": "קיבוץ כפר עזה",
    "Last Seen Comments": "Kibbutz kfar Aza",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Damaris Raab (מריסה)",
    "First Name": "Damaris",
    "Last Name": "Raab (מריסה)",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "דגמר שלו",
    "Reporter relation": "NA",
    "Reporter Phone": "549760256",
    "Reporter Email": "eliyalavi1@gmail.com",
    "Last hour of contact": "אתמול בערב",
    "Report from reporter": "\"מתנדבת מגרמניה",
    "Last seen location": " הייתה אמורה לחזור הביתה אתמול היה הקשר האחרון איתה בזמן שהתחבאה בממ״ד מאז הקשר אבד\"",
    "Last Seen Comments": "לא ידוע",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "אזרח",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "גוון בהיר",
    "Hair Color": "בהיר",
    "Height": "בהיר",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Gali Taraschansky",
    "First Name": "Gali",
    "Last Name": "Taraschansky",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Viktoria",
    "Reporter relation": "NA",
    "Reporter Phone": "+79647077949",
    "Reporter Email": "chervonnaya.vp@gmail.com",
    "Last hour of contact": "07.10.2023 11:30",
    "Report from reporter": "child disappeared on the territory of kibbutz beeri as a result of escaping from terrorists",
    "Last seen location": "beeri",
    "Last Seen Comments": "beeri",
    "Soldier/Civilian": "אזרח",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Karla Stelzer Mendes",
    "First Name": "Karla",
    "Last Name": "Stelzer Mendes",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "Patricia Hallak",
    "Reporter relation": "NA",
    "Reporter Phone": "0506568111 0533334860",
    "Reporter Email": "patyhallak@hotmail.com  Filipasantoscosta@gmail.com",
    "Last hour of contact": ": בשעה 8:11 היא שלחה אודיו בוואטסאפ",
    "Report from reporter": "היא הייתה במסיבה בדרום. שלח אודיו ווידאו כשהוא נמלט. באודיו האחרון היא אמרה שהיא הייתה בבונקר שבו טרוריסטים זרקו פצצה והיא הצליחה להימלט  She is Brazilian  She was with the boyfriend in the party his name is Gabi Azulay- also still missing ! Please fast let me know something !!!",
    "Last seen location": "מסיבה בדרום",
    "Last Seen Comments": "היא הייתה במסיבה בדרום",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "בהיר",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Lior Taraschansky",
    "First Name": "Lior",
    "Last Name": "Taraschansky",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "Viktoria",
    "Reporter relation": "NA",
    "Reporter Phone": "+79647077949",
    "Reporter Email": "chervonnaya.vp@gmail.com",
    "Last hour of contact": "07.10.2023 11:30 a.m",
    "Report from reporter": "a child was left in a burning house on the territory of Kibbutz Beeri",
    "Last seen location": "Beeri",
    "Last Seen Comments": "Beeri",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Lorie Alacre",
    "First Name": "Lorie",
    "Last Name": "Alacre",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "נועם סולומון",
    "Reporter relation": "NA",
    "Reporter Phone": "506623329",
    "Reporter Email": "noamsw88@gmail.com",
    "Last hour of contact": "\"אתמול בשעות הבוקר המוקדמות",
    "Report from reporter": " אחותה מהפיליפינים דיברה איתה\"",
    "Last seen location": "\"החבר שהיא היתה איתו",
    "Last Seen Comments": " מאושפז בבית חולים ברזילי במחלקה הכירורגית כי נפגע מירי בגב",
    "Soldier/Civilian": " אין פרטים מה קורה ללורי שלי :(\"",
    "Military ID (Mispar Ishi)": "\"בין נתיבות לאשקלון",
    "Address": " ליד מטה בוטנים\"",
    "Physical description": "\"בין נתיבות לאשקלון",
    "Eye color": " ליד מטה בוטנים\"",
    "Hair Color": "לא ידוע",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "גוון בהיר",
    "Marks on the body": "כהה",
    "Social Media": "כהה",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Orion hernandez",
    "First Name": "Orion",
    "Last Name": "hernandez",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "רתם כהן",
    "Reporter relation": "NA",
    "Reporter Phone": "506500922",
    "Reporter Email": "Jesus6853@gmail.com",
    "Last hour of contact": "במסיבה ברעים",
    "Report from reporter": "בחור מקסיקני לא דובר עברית כל המשפחה שלו במקסיקו אני האיש הקשר שמקושר עם המשפחה שלו וחברה שלו הישראלית נרצחה ונרצחה באירוע של הנובה",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "במסיבה ברעים",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "\"קעקועים על כל הידיים",
    "Social Media": " טרייבלים עד הצוואר כולל. כתובת בערבית על החזה.\"",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Ranani Glazer / רנני גלזר",
    "First Name": "Ranani",
    "Last Name": "Glazer",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע    זכר",
    "Reporter name": "Jussara martins    דניאל",
    "Reporter relation": "NA",
    "Reporter Phone": "0506798027 0506710235    523624190",
    "Reporter Email": "Jussara_copa@gmail.com",
    "Last hour of contact": "09:30    לפני המסיבה של נובה",
    "Report from reporter": "הוא יהודי שגר בפורטו אלגרו והגיע לישראל עםעוד תיירת ששמה לא ידוע",
    "Last seen location": "דרום",
    "Last Seen Comments": "לא    דרום",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה    גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "\"קעקוע גדול על בית החזה",
    "Social Media": " שני קעקועים על זרוע ימין קעקוע במרכז הבטן     קעקוע גדול על החזה ידיים (כמו בקפלה הסיסטנית)",
    "Data to verify": " קעקועים גדולים על זרוע עליונה\"",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "Soslyuk Vadym",
    "First Name": "Soslyuk",
    "Last Name": "Vadym",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "Soslyuk Stanislav",
    "Reporter relation": "NA",
    "Reporter Phone": "+79093196144",
    "Reporter Email": "v.gorelnikova@gmail.com",
    "Last hour of contact": "3  month ago",
    "Report from reporter": "Citizen of Ukrain . He can be in a jail.",
    "Last seen location": "Haifa",
    "Last Seen Comments": "Haifa",
    "Soldier/Civilian": "אזרח",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "NA",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אאליקים שלמה",
    "First Name": "אאליקים",
    "Last Name": "שלמה",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "אושרה ליבמן",
    "Reporter relation": "NA",
    "Reporter Phone": "058-6377449",
    "Reporter Email": "Oshralivman1@gmail.com",
    "Last hour of contact": "09:00",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "מסיבה ברעים",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבו עצא אוסמה",
    "First Name": "אבו - עצא",
    "Last Name": "אוסמה",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "טלאלקה פאד",
    "Reporter relation": "NA",
    "Reporter Phone": "542590483",
    "Reporter Email": "F.h.d_988@hotmail.co.il",
    "Last hour of contact": "07:30",
    "Report from reporter": "NA",
    "Last seen location": "רעים",
    "Last Seen Comments": "מושב רעים",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "ללא שיער",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי דדון",
    "First Name": "אבי",
    "Last Name": "דדון",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "רוויטל בן דוד    ויקי בוטמן",
    "Reporter relation": "NA",
    "Reporter Phone": "0523047606 0506308060 053-9662607    544503966",
    "Reporter Email": "hadarb85@gmail.com",
    "Last hour of contact": "9:00 / 14:00 7.10    קצת לפני תשע בבוקר",
    "Report from reporter": "תשע בבוקר / שנלקח הטלפון בסביבות שתיים בצהריים 7.10",
    "Last seen location": "\"מסיבת נובה    ליד המסיבה",
    "Last Seen Comments": " קיבוץ רעיה\"",
    "Soldier/Civilian": "רעים מסיבת טבע / מסתתתרים בשטח ליד המסיבה / קיבוץ רעיה    מסתתתרים בשטח ליד המסיבה / קיבוץ רעיה",
    "Military ID (Mispar Ishi)": "לא ידוע",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "גוון כהה",
    "Hair Color": "כהה",
    "Height": "כהה",
    "Body type": "גבוה",
    "Clothes wearing": "רזה",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי הינדי",
    "First Name": "אבי",
    "Last Name": "הינדי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "גל מורן",
    "Reporter relation": "NA",
    "Reporter Phone": "507574006",
    "Reporter Email": "NA",
    "Last hour of contact": "07:00",
    "Report from reporter": "NA",
    "Last seen location": "כפר עזה",
    "Last Seen Comments": "כפר עזה",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי זקוטו",
    "First Name": "אבי",
    "Last Name": "זקוטו",
    "Mobile": "NA",
    "Status Original": "הרוג",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "עדי זקוטו",
    "Reporter relation": "NA",
    "Reporter Phone": "0503542493 0558850534 0503542494",
    "Reporter Email": "Adizakuto1999@gmail.com",
    "Last hour of contact": "06:45",
    "Report from reporter": "\"ב 6.30 בבוקר בתקשרו להזהיר אותו שיש מחבלים הוא התעצבן שהעירו אותו אבל מ אז הוא יותר לא זמין דיברנו עם בעלת הבית שבו הוא שוכר דירה היא אמרה שהיא לא יודעת מה קורה היא נעולה עם הילדות בממד ושהיא מצטערת אבל אחרי זה הקשר נותק כם איתה וגם היא לא עונה אין מענה מ7 בבוקר",
    "Last seen location": " התקשרנו למשטרה",
    "Last Seen Comments": " מדא",
    "Soldier/Civilian": " פיקוד העורף",
    "Military ID (Mispar Ishi)": " בתי החולים",
    "Address": " הרווחה",
    "Physical description": " שכנים ועובדים ואף אחד לא יודע מה קורה.\"",
    "Eye color": "אופקים",
    "Hair Color": "NA",
    "Height": "לא ידוע",
    "Body type": "NA",
    "Clothes wearing": "\"אתרוג 9",
    "Marks on the body": " אופקים\"",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי חסדאי",
    "First Name": "אבי",
    "Last Name": "חסדאי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "NA",
    "Reporter name": "אלי נחום",
    "Reporter relation": "NA",
    "Reporter Phone": "507669967",
    "Reporter Email": "Elinachun2@gmail.com",
    "Last hour of contact": "06:46",
    "Report from reporter": "NA",
    "Last seen location": "חוף זיקים",
    "Last Seen Comments": "חוף זיקים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "בהיר",
    "Hair Color": "בהיר",
    "Height": "גבוה",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי מועלם",
    "First Name": "אבי",
    "Last Name": "מועלם",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "שירלי אסולין",
    "Reporter relation": "NA",
    "Reporter Phone": "528409388",
    "Reporter Email": "shirleyas1975@gmail.com",
    "Last hour of contact": "07:00",
    "Report from reporter": "הינו יחד כשהתחילו להפגיז ולירות אני נכנסתי לרכב וברחתי והבנתי שהוא נסע קצת לפני. הטלפון שלו נמצא זרוק על ידי בחורים שברחו מהנובה.",
    "Last seen location": "חוות טל אור",
    "Last Seen Comments": "חוות טל אור/פטיש",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "NA",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבי סאסי",
    "First Name": "אבי",
    "Last Name": "סאסי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "עדן מאירי",
    "Reporter relation": "NA",
    "Reporter Phone": "527755966",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "NA",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביאל אורן",
    "First Name": "אביאל",
    "Last Name": "אורן",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "יסמין אורן",
    "Reporter relation": "NA",
    "Reporter Phone": "050-9267766 0502682233 0524574421",
    "Reporter Email": "jasminlc50@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "לאביאל יש שני קעקועים של אננס עם משקפי שמש ותווי נגינה ברגל השנייה.  ירו להם על הרכב החבר הצליח ליצור קשר ולעדכן שירו בהם והם מחכים לחילוץ אביאל והחברים התהפכו ברכב לאחר ירי צרורות באיזור המסיבה ברעים. חלק מהחברים הצליחו להמלט אבל אביאל נשאר בשטח. אנחנו לא יודעים עוד פרטים. נראה אתמול בערב",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "מסיבת טבע ברעים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "אננס עם משקפי שמש על רגל אחת - תווי נגינה על רגל השנייה.",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביאל רחמים",
    "First Name": "אביאל",
    "Last Name": "רחמים",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "הילה רחמים",
    "Reporter relation": "NA",
    "Reporter Phone": "+972 53-226-2282 0523765208 0547895152 0544553035 0523141997 0524339616",
    "Reporter Email": "safit124@gmail.com",
    "Last hour of contact": "06:45",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "\"בארי / במסיבה במושב רעים",
    "Soldier/Civilian": "\"",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב אליהו",
    "First Name": "אביב",
    "Last Name": "אליהו",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "שובל ברדר",
    "Reporter relation": "NA",
    "Reporter Phone": "0525148150 0522823537",
    "Reporter Email": "Liron.cohen022@gmail.com",
    "Last hour of contact": "07:50",
    "Report from reporter": "הוא מנבט באבטחה שאבטחו את המסיבה ברעים יודעים שהוא היה בקו אש עם המחבלים ומשם אין לנו קשר איתו",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "פסטיבל נובה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב אצילי",
    "First Name": "אביב",
    "Last Name": "אצילי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "נורית אצילי",
    "Reporter relation": "NA",
    "Reporter Phone": "+61499599517 0526108099",
    "Reporter Email": "nuritatzili@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "\"דיברתי עם אשתו",
    "Last seen location": " ליאת",
    "Last Seen Comments": " בבוקר ולא שמעתי מהם מאז. לא עונים לווטסאפ או טלפון. שמעו לאחרונה אתמול מוקדם בבוקר.\"",
    "Soldier/Civilian": "ניר עוז",
    "Military ID (Mispar Ishi)": "חבר קיבוץ ניר עוז",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "גוון בהיר",
    "Height": "כהה",
    "Body type": "כהה",
    "Clothes wearing": "גבוה",
    "Marks on the body": "בינוני",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב אשר",
    "First Name": "אביב",
    "Last Name": "אשר",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "יוני אשר",
    "Reporter relation": "NA",
    "Reporter Phone": "050-2006090",
    "Reporter Email": "Shiranasher1981@gmail.com",
    "Last hour of contact": "7.10 11:00",
    "Report from reporter": "\"דורון אשר",
    "Last seen location": " רז אשר",
    "Last Seen Comments": " אביב אשר",
    "Soldier/Civilian": " אפשרת כץ\"",
    "Military ID (Mispar Ishi)": "חאן יונס",
    "Address": "חאן יונס",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב ברעם",
    "First Name": "אביב",
    "Last Name": "ברעם",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "סיגל פז",
    "Reporter relation": "NA",
    "Reporter Phone": "0546804946 שרה ברעם 0506686534 איילת סהלו 0523745561 אורי ברעם 0546804945 0544646308",
    "Reporter Email": "Sigalpp@gmail.com",
    "Last hour of contact": "07:30",
    "Report from reporter": "07:30 הודיע שירו עליו ומאז נותק הקשר היה בכיתת כוננות ונפצע לא ידוע אם פונה ולאן",
    "Last seen location": "כפר עזה",
    "Last Seen Comments": "כפר עזה ליד מחסן נשק",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "מלא",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב דהן",
    "First Name": "אביב",
    "Last Name": "דהן",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "יובל אילייב",
    "Reporter relation": "NA",
    "Reporter Phone": "\"0548198191 אור דהן אחותו הגדולה 0584349833",
    "Reporter Email": " 0506806053 יובל וליאם- חברים טובים\"",
    "Last hour of contact": "Yuvaleliav00@gmail.com",
    "Report from reporter": "NA",
    "Last seen location": "הבן אדם גר בשכונת תל כביר מי שמוצא להתקשר דחוף לאחד מהטלפונים. התגלה לי על זה היום בבוקר",
    "Last Seen Comments": "חוף הילטון",
    "Soldier/Civilian": "חוף הילטון בו נמצא לאחרונה",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב עוז",
    "First Name": "אביב",
    "Last Name": "עוז",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "NA",
    "Reporter relation": "NA",
    "Reporter Phone": "NA",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "\"מידע אוטומטי מטבלת נעדרים 1Ck6rH3540-mTSLYq6QYBUiMwSgQCNLoiqghjcc7O1-g\"",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביב קוץ",
    "First Name": "אביב",
    "Last Name": "קוץ",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "טליה קוץ שמיר",
    "Reporter relation": "NA",
    "Reporter Phone": "547714625",
    "Reporter Email": "taliksh@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "אין קשר מאתמול",
    "Last seen location": "כפר עזה",
    "Last Seen Comments": "כפר עזה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "ללא שיער",
    "Height": "בינוני",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביגיל אלטר",
    "First Name": "אביגיל",
    "Last Name": "אלטר",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "מרגלית דהן",
    "Reporter relation": "NA",
    "Reporter Phone": "542486109",
    "Reporter Email": "Eternalkonstantin@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "תום עטר אביגיל אלטר יואב מישקין דיאגו אלטר שי דומאני  אור חרמוני נועה חיאל גידי חיאל לירון ברבה זיו הגבאי. אין קשר מהלילה",
    "Last seen location": "NA",
    "Last Seen Comments": "כן",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבידן תורג'מן",
    "First Name": "אבידן",
    "Last Name": "תורג'מן",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "מיכאל תורג'מן האב",
    "Reporter relation": "אב",
    "Reporter Phone": "0505965672 0524556502 0525105744 0506411016 0507753211 0502213948",
    "Reporter Email": "moniquemuddyhands@gmail.com",
    "Last hour of contact": "7/10 9.30",
    "Report from reporter": "דרך המשטרה איכון אחרון של הפלפון ב13.30 בבארי  היה במסיבה ברעים כשהמחבלים הגיעו התחבה מתחת לבמה לא ידוע אם הצליח לצאת משן",
    "Last seen location": "רעים",
    "Last Seen Comments": "רעים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "בהיר",
    "Hair Color": "בהיר",
    "Height": "גבוה",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביה",
    "First Name": "אביה",
    "Last Name": "NA",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "לא ידוע",
    "Reporter name": "526454977",
    "Reporter relation": "NA",
    "Reporter Phone": "NA",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "\"מידע אוטומטי מטבלת נעדרים 1Ck6rH3540-mTSLYq6QYBUiMwSgQCNLoiqghjcc7O1-g\"",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביה גנוט",
    "First Name": "אביה",
    "Last Name": "גנוט",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "מנחם גנוט",
    "Reporter relation": "NA",
    "Reporter Phone": "0528249924 0525122333 052-220-5524 0507980016 0528321392 0549197599 0504283370 0525522277",
    "Reporter Email": "mgenut@h-o.co.il",
    "Last hour of contact": "09:00",
    "Report from reporter": "יש לה קעקוע של לביאה על הגב וברכת כוהנים על פנים הזרוע",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "מסיבה ברעים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "קעקוע של לביאה על הגב וברכת כוהנים על פנים הזרוע",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביה גנות",
    "First Name": "אביה",
    "Last Name": "גנות",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "מלני פרוביץ",
    "Reporter relation": "NA",
    "Reporter Phone": "522940481",
    "Reporter Email": "Melany.da@hotmail.com",
    "Last hour of contact": "09:00",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "במסיבה ברעים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "בהיר",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביטל דקל חן",
    "First Name": "אביטל",
    "Last Name": "דקל חן",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "ניצן דגן",
    "Reporter relation": "NA",
    "Reporter Phone": "506480244",
    "Reporter Email": "nitzanda@gmail.com",
    "Last hour of contact": "בוקר צהריים",
    "Report from reporter": "NA",
    "Last seen location": "ניר עוז",
    "Last Seen Comments": "ניר עוז",
    "Soldier/Civilian": "לא ידוע",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביטן דור",
    "First Name": "אביטן",
    "Last Name": "דור",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "אביטן ויקי    ורוניקה",
    "Reporter relation": "NA",
    "Reporter Phone": "544801621    507639337",
    "Reporter Email": "Vikiavi2812@gmail.com    veropolo2604@gmail.com",
    "Last hour of contact": "08:15",
    "Report from reporter": "היה לו בסטה של תכשיטים במסיבה    קשר אחרון שילשום",
    "Last seen location": "רעים    מסיבת נובה",
    "Last Seen Comments": "רעים    מסיבת נובה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "בהיר",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "V",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבינתן אור",
    "First Name": "אבינתן",
    "Last Name": "אור",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "דולב קיקוס",
    "Reporter relation": "NA",
    "Reporter Phone": "524389065",
    "Reporter Email": "Dolevkikos@gmail.com",
    "Last hour of contact": "10:20",
    "Report from reporter": "NA",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "נובה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביעד אדרי",
    "First Name": "אביעד",
    "Last Name": "אדרי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "ישראל אדרי",
    "Reporter relation": "NA",
    "Reporter Phone": "0559342376 0544627099",
    "Reporter Email": "Etiharush@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "קשר אחרון היום בבוקר",
    "Last seen location": "כפר עזה",
    "Last Seen Comments": "קיבוץ כפר עזה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביעד ריבלין",
    "First Name": "אביעד",
    "Last Name": "ריבלין",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "עומר אברגל    קטיה",
    "Reporter relation": "NA",
    "Reporter Phone": "050-519-5798  0523264528    526283881",
    "Reporter Email": "284omer@gmail.com    Katyamasover@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "\"חייל בודד",
    "Last seen location": " לא בקשר עם הוריו רק עם אחיו. נא ליצור איתי קשר עומר העוסית שלו. קשר אחרון ביום שישי בערב    מפרסמת עבור חבר",
    "Last Seen Comments": " זה אח וחבר שלו. אח אחר שלו נרצח במסיבה. מופיע בתמונה משמאל. קשר אחרון בבוקר\"",
    "Soldier/Civilian": "מסיבת נובה    רעים",
    "Military ID (Mispar Ishi)": "היה במסיבה בנובה    רעים",
    "Address": "חייל",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "גוון בהיר",
    "Height": "בהיר    כהה",
    "Body type": "כהה",
    "Clothes wearing": "NA",
    "Marks on the body": "רזה",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "NA"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אבישג עובד",
    "First Name": "אבישג",
    "Last Name": "עובד",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "נקבה",
    "Reporter name": "יגור קפלן",
    "Reporter relation": "NA",
    "Reporter Phone": "053-5330763",
    "Reporter Email": "kaplanyegor@gmail.com",
    "Last hour of contact": "11:39",
    "Report from reporter": "היא היתה עם בת דודה שלה בשם אביה בתוך אוהל היא פצועה עם פצע פתוח בברך! הן מאחורי בדים ורודים ליד אמבולנס שעלה באש",
    "Last seen location": "רעים",
    "Last Seen Comments": "מערבית לכביש 232 ביער ליד רעים",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביתר דוד",
    "First Name": "אביתר",
    "Last Name": "דוד",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "נגה גוטמן",
    "Reporter relation": "NA",
    "Reporter Phone": "545883555",
    "Reporter Email": "nogaguttman@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "קשר אחרון יום שבת בבוקר",
    "Last seen location": "מסיבת טבע",
    "Last Seen Comments": "מסיבת טבע",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון כהה",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביתר לוי",
    "First Name": "אביתר",
    "Last Name": "לוי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "NA",
    "Reporter relation": "NA",
    "Reporter Phone": "NA",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "\"מידע אוטומטי מטבלת נעדרים 1Ck6rH3540-mTSLYq6QYBUiMwSgQCNLoiqghjcc7O1-g\"",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אביתר קיפניס",
    "First Name": "אביתר",
    "Last Name": "קיפניס",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "מאי",
    "Reporter relation": "NA",
    "Reporter Phone": "525258700",
    "Reporter Email": "NA",
    "Last hour of contact": "09:30",
    "Report from reporter": "NA",
    "Last seen location": "בארי",
    "Last Seen Comments": "קיבוץ בארי",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "NA",
    "Hair Color": "בהיר",
    "Height": "NA",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם - רמי קציר",
    "First Name": "אברהם",
    "Last Name": "רמי קציר",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "שקד שי",
    "Reporter relation": "NA",
    "Reporter Phone": "544846326",
    "Reporter Email": "Shaked15001@gmail.com",
    "Last hour of contact": "10:00",
    "Report from reporter": "\"התבצר יחד עם אשתו חנה קציר בממד ",
    "Last seen location": " נותר עימם הקשר בשעות הבוקר כאשר דווח שמחבלים נכנסו לקיבוץ וברקע עם השיחה יריות.\"",
    "Last Seen Comments": "ניר עוז",
    "Soldier/Civilian": "ניר עוז",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "גוון בהיר",
    "Hair Color": "NA",
    "Height": "בהיר",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם גילעד טיברג",
    "First Name": "אברהם",
    "Last Name": "גילעד טיברג",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "שחר",
    "Reporter relation": "NA",
    "Reporter Phone": "507391469",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "קשר אחרון אתמול",
    "Last seen location": "מסיבת נובה",
    "Last Seen Comments": "המסיבה",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "גבוה",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם זקוטו",
    "First Name": "אברהם",
    "Last Name": "זקוטו",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "יניב זכאי",
    "Reporter relation": "NA",
    "Reporter Phone": "546266635",
    "Reporter Email": "Yanivzakai@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "NA",
    "Last seen location": "אופקים",
    "Last Seen Comments": "אופקים רחוב האתרוג",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "NA",
    "Hair Color": "NA",
    "Height": "NA",
    "Body type": "NA",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם חננאל הינדי",
    "First Name": "אברהם",
    "Last Name": "חננאל הינדי",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "אסתי צילקר",
    "Reporter relation": "NA",
    "Reporter Phone": "546446910",
    "Reporter Email": "Estizilker@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "\"בעלה של שחר ואבא ל 3 ילדים.  אבי חלק מכיתת הכוננות בקיבוץ כפר עזה",
    "Last seen location": " ידוע כי נפצע אתמול בבוקר בחילופי האש מול המחבלים ומאז נותק הקשר עמו וכל מידע עליו. קשר אחרון אתמול בבוקר\"",
    "Last Seen Comments": "כפר עזה",
    "Soldier/Civilian": "כפר עזה",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "NA",
    "Eye color": "גוון כהה",
    "Hair Color": "כהה",
    "Height": "כהה",
    "Body type": "גבוה",
    "Clothes wearing": "בינוני",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "NA",
    "\r": "X"
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם טיברג",
    "First Name": "אברהם",
    "Last Name": "טיברג",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "מאיה נתנזון",
    "Reporter relation": "NA",
    "Reporter Phone": "526411041",
    "Reporter Email": "NA",
    "Last hour of contact": "NA",
    "Report from reporter": "NA",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "כהה",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "רזה",
    "Clothes wearing": "NA",
    "Marks on the body": "NA",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
  {
    "name": "NA",
    "Subitems": "NA",
    "Full name": "אברהם כהן",
    "First Name": "אברהם",
    "Last Name": "כהן",
    "Mobile": "NA",
    "Status Original": "נעדר",
    "Status": "NA",
    "Last Updated": "NA",
    "Additional information": "NA",
    "Source": "NA",
    "Tehudat Zehut": "NA",
    "Passport": "NA",
    "Comments": "NA",
    "Missing person Email": "NA",
    "Age": "NA",
    "Gender": "זכר",
    "Reporter name": "רותם בונומו",
    "Reporter relation": "NA",
    "Reporter Phone": "522566460",
    "Reporter Email": "rotembonomo12@gmail.com",
    "Last hour of contact": "NA",
    "Report from reporter": "אין לי שום מידע עליהם לא הייתי איתם הם לא.בשום רשימה של נעדרים שנמצאו ואין זכר אף אחד לא ראה אותם אני פשוט מתפללת יש לו קעקוע שחור על כל היד יונתן היה פצוע ברגליים כל השאר לא יודעים",
    "Last seen location": "NA",
    "Last Seen Comments": "NA",
    "Soldier/Civilian": "NA",
    "Military ID (Mispar Ishi)": "NA",
    "Address": "NA",
    "Physical description": "גוון בהיר",
    "Eye color": "בהיר",
    "Hair Color": "כהה",
    "Height": "בינוני",
    "Body type": "בינוני",
    "Clothes wearing": "NA",
    "Marks on the body": "קעקוע שחור אטום ביד ימין עד האגודל (השחיר את כל הזרוע) קעקוע בכתף שמאל צורת עיגול",
    "Social Media": "NA",
    "Data to verify": "NA",
    "PER ID - suspected duplicates": "NA",
    "duplicate group id": "X",
    "\r": null
  },
];